apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cheese
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: a8ded8d93541511eaae130647dd02e98-d7f03538569249f4.elb.us-west-2.amazonaws.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cheddar
          servicePort: 80 