apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cheese
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ad3b967f554dc11ea9806063baceb300-03e199521b6f644a.elb.us-west-2.amazonaws.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cheddar
          servicePort: 80 

